export const musicInfoMockData = {
  kind: 'track',
  id: 412411872,
  created_at: '2018/03/12 08:53:08 +0000',
  user_id: 183259456,
  duration: 189875,
  commentable: true,
  state: 'finished',
  original_content_size: 7591680,
  last_modified: '2018/04/11 04:29:53 +0000',
  sharing: 'public',
  tag_list: '',
  permalink: '01-agape-title',
  streamable: true,
  embeddable_by: 'all',
  purchase_url: null,
  purchase_title: null,
  label_id: null,
  genre: 'Jazz & Blues',
  title: '01. Agape [title]',
  description:
    'To. Mom and G.F\n\nVerse1) Tamiz\n\n우린 일욜 마다 \n교회 나가\n사랑을 갈구하네\n\n아가페 사랑을\n주신 우리 예수 님께\n\nyou re beautiful\n손잡구 둘이서\n예배 드리구 \n\n예배중 몰래\n데이트팝  \n클릭후\n먹거리\n눈팅두 \n\n다 끝냈어 \n"오늘은 혜화 어때"\n \n내가 좀 알아 봤지 훗 \n너는 개설렌데 \n\n딴새끼들 다하는건데도  \n넌 내게 재깍 건네 \n\n너가 준  \n칭찬들을 가지고 난\n오늘도 쪼여 버려 \n광대뼈 hey\n\n숙대입구\n역으로 가는 길\n노숙자 아저씨\n를 보며 눈물 흘리는 너의 마음씨\n거기에 난 \n놀랐지\n\n여타 지금까지 내가 본\n기독교인들과는 넌 달러\n내가 예수님을 믿는건\n너에게서 본\n아가페 덕이지 uh\n\nHook) Tamiz\n\n아가페 아가페 사랑에 빠졌네\n아가돼 아가돼 니앞에만 서면 나 x2 \n아가페 아가페\n\nVerse2) Tamiz\n\n우린 일욜 마다 \n교회 나가\n화목을 갈구했었네\n\n아가페 사랑\n주신 우리 예수 님께\n\nyou re beautiful\n손잡구 넷이서\n예배 드리구 \n\n예배중 몰래\n엄마 눈을\n피해  \n꾸벅꾸벅 \n졸다 언제 든지 \n \n도망갈 준비를 해\n그러다 새장에서 비행\n한지  \nmay be\nthree year\n\n그냥 그녀의 눈초리\n가 싫어서\n길게 끌었지 중2\n병\n\n그녀의 마음에 생채기\n를 내기도 했고\n\n내맘에 낸 생채기를\n보며 원망도 했어\n\n황소고집 피워 \n그녀와 하루 종일 집만가면\n열렸어 투우 경기 해\n\n계속 지쳐 \n계속 기도\n한다면서 \n\n믿음\n이 있으면 뭐해\n\n새벽기도\n가면 뭐하냐고\n엄마  \n그럴 시간에 날 더 \n이해좀 해\n\n신은 없는 것 같어 \n아니 모르는 것 같기도\n아니 지금 보니\n내가 예수님을 믿었던 건 그녀에게서\n봤던 아가페 덕이니 \n\nHook) Tamiz\n\n아가페 아가페 사랑에 빠졌네\n아가돼 아가돼 그녀 앞에만 서면 나 x2\n아가페 아가페\n\n-------------------------------\n\nInst.T-Pain - Chopped N Skrewed , Beenzino"나이야가라"remix\nLyrics by Tamiz \nMixed & Mastered by Tamiz',
  label_name: null,
  release: null,
  track_type: null,
  key_signature: null,
  isrc: null,
  video_url: null,
  bpm: null,
  release_year: 2018,
  release_month: 3,
  release_day: 12,
  original_format: 'mp3',
  license: 'all-rights-reserved',
  uri: 'https://api.soundcloud.com/tracks/412411872',
  user: {
    id: 183259456,
    kind: 'user',
    permalink: 'ibrtamiz',
    username: 'TamiZ',
    last_modified: '2018/10/06 14:42:01 +0000',
    uri: 'https://api.soundcloud.com/users/183259456',
    permalink_url: 'http://soundcloud.com/ibrtamiz',
    avatar_url: 'https://i1.sndcdn.com/avatars-000346578854-zir47u-large.jpg',
  },
  permalink_url: 'https://soundcloud.com/ibrtamiz/01-agape-title',
  artwork_url: 'https://i1.sndcdn.com/artworks-000314954319-mz4e1k-large.jpg',
  stream_url: 'https://api.soundcloud.com/tracks/412411872/stream',
  download_url: 'https://api.soundcloud.com/tracks/412411872/download',
  playback_count: 2199,
  download_count: 0,
  favoritings_count: 52,
  reposts_count: 5,
  comment_count: 1,
  downloadable: false,
  waveform_url: 'https://w1.sndcdn.com/uDo0oFXaDIes_m.png',
  attachments_uri: 'https://api.soundcloud.com/tracks/412411872/attachments',
};

export const historyMockData = {
  data: {
    kind: 'track',
    id: 331622174,
    created_at: '2017/07/05 08:08:39 +0000',
    user_id: 214535905,
    duration: 186479,
    commentable: true,
    state: 'finished',
    original_content_size: 7449984,
    last_modified: '2018/02/13 00:41:36 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'feat-planet',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Hip-hop & Rap',
    title: '지금 뭐 해 (feat. PLANET)',
    description:
      "Lyrics by  Bluite  ,  PLANET\nMixed by PLANET\nArtwork by Tomnick\nProduced by Bluesy Mansion\n\nverse 1 ) Bluite\n\n아침에 하는 건 알람 끄기 밖에 없던 내가\n요즘은 일어나 하는 건 네 상메 확인부터야\n\n점심에 하는 건 약속 잡는 것 밖에 없던 내가\n요즘은 시간 비우는 걸, 아, 니 연락 기다리나봐\n\n저녁에 하는 건 술 먹는 것 밖에 없던 내가\n요즘은 뭐라고 보낼까, 고민만 한 시간 째야\n\n처음 만났던 그때를 기억해 난\n넌 ~ 남방을 입었었지, 한\n\n참을 바라 봤고 말을 걸까도 했어\n아,아 근데 내 스타일은 아냐\n\n내려다보는 눈빛이 설레, 몰래\n감정을 숨기고 또 표현, 못하는 게 나야\n\n그게 말야, 난 모든 게 처음이니\n서툰 날, 조금만 더 맞춰줄래\n\nhook) Bluite\n\nlove is painful 이건 너무도 말이 안돼\nlove is an open door love is an open door\n\nlove is painful 이건 너무도 말이 안돼\nlove is an open door love is an open door\n\nverse 2) PLANET\n\n예 사실 너가 그렇게 신경 쓰이고 했던  건 별로 아니었기에\n처음에는 그냥 생각 없이 너에게 다가갔고\n설레어 하는 듯, 한 너가 귀엽기만 했어\n\n근데 솔직히 말할게 I can't predict it \n예상 못했는데 너가 내 삶에 그렇게\n큰 부분을 차지할진 몰랐고\n너가 내 맘 한, 켠 에서 계속 돌고 돌아\n\n자고 일어나면 자연스럽게 take a message\n너가 황새라면 난 영원히 널 쫒는 뱁새지\n찢어져도 좋아 가랑인\n언제부턴가 널 보는 날이면 산뜻한 신바람이\n\n불어와 don't leave me alone \n너도 나와 같다면 지금당장 날 보러와\n조바심이 나기 시작해 어느 순간 나는\n답장만 빨라지는 걸 babe \n\nhook) Bluite X PLANET\n\nlove is painful 이건 너무도 말이 안돼\nlove is an open door love is an open door\n\nlove is painful 이건 너무도 말이 안돼\nlove is an open door love is an open door\n\nbridge ) Bluite\n\n너 지금 뭐해\n난 답장 느린 걸 좋아 해\n\n질투는 없어 하나도\n근데 너 때문에 변해 또\n\n넌 어떻게 생각 해 지금 우리 사이\n뭐 이렇게 복잡해 시간 지나 많이\n\n생각 많이 했다간 놓칠 거야. 뭘 바라지\n않아, 조금만 네가 다가오지\n\nLyrics by  Bluite  ,  PLANET\nMixed by PLANET\nArtwork by Tomnick\nProduced by Bluesy Mansion",
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/331622174',
    user: {
      id: 214535905,
      kind: 'user',
      permalink: 'lxwl4ih4tphn',
      username: 'Bluite',
      last_modified: '2018/07/07 10:47:51 +0000',
      uri: 'https://api.soundcloud.com/users/214535905',
      permalink_url: 'http://soundcloud.com/lxwl4ih4tphn',
      avatar_url: 'https://i1.sndcdn.com/avatars-000378492338-8vchg6-large.jpg',
    },
    permalink_url: 'https://soundcloud.com/lxwl4ih4tphn/feat-planet',
    artwork_url: 'https://i1.sndcdn.com/artworks-000232037629-yspo52-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/331622174/stream',
    download_url: 'https://api.soundcloud.com/tracks/331622174/download',
    playback_count: 2730,
    download_count: 0,
    favoritings_count: 58,
    reposts_count: 5,
    comment_count: 2,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/hounJmQBrjAK_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/331622174/attachments',
  },
  status: 200,
  statusText: 'OK',
  headers: {
    date: 'Sun, 02 Dec 2018 17:24:25 GMT',
    'content-type': 'application/json;charset=utf-8',
    'cache-control': 'private, max-age=0, must-revalidate',
  },
  config: {
    transformRequest: {},
    transformResponse: {},
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    headers: {
      Accept: 'application/json, text/plain, */*',
    },
    method: 'get',
    url:
      '//api.soundcloud.com/tracks/331622174?client_id=a281614d7f34dc30b665dfcaa3ed7505',
  },
  request: {},
};
