export const SELECT_SONG = 'SELECT_SONG';
export const FETCH_NEW_STREAM_SONGS_SUCCESS = 'FETCH_NEW_STREAM_SONGS_SUCCESS';
export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';